import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-real-estate-brokerage-commission-reconciliation",
  "engine": "recovery",
  "title": "Real Estate Brokerage Commission Reconciliation",
  "shortTitle": "Real Estate Brokerage Commission Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through real estate brokerage commission reconciliation",
  "industry": "Real Estate Commission Operations",
  "uiPort": 4615,
  "apiPort": 5615,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Real Estate Brokerage Commission Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidCommission",
    "expectedKey": "earnedCommission",
    "actualLabel": "Paid Commission",
    "expectedLabel": "Calculated Earned Commission",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Real Estate Brokerage Commission Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("agreement-library","REB01","Agreement library","Execute agreement library using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Agreement library Reference","text","REB01-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("property-transaction-registry","REB02","Property transaction registry","Execute property transaction registry using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed property transaction registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Property transaction registry Reference","text","REB02-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("closing-statement-ingestion","REB03","Closing statement ingestion","Execute closing statement ingestion using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed closing statement ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Closing statement ingestion Reference","text","REB03-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("gross-commission-calculation","REB04","Gross commission calculation","Execute gross commission calculation using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed gross commission calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Gross commission calculation Reference","text","REB04-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("co-broker-split-validation","REB05","Co-broker split validation","Execute co-broker split validation using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed co-broker split validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Co-broker split validation Reference","text","REB05-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("agent-split-calculation","REB06","Agent split calculation","Execute agent split calculation using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed agent split calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Agent split calculation Reference","text","REB06-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("team-referral-allocation","REB07","Team referral allocation","Execute team referral allocation using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed team referral allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Team referral allocation Reference","text","REB07-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("franchise-desk-fee-audit","REB08","Franchise desk fee audit","Execute franchise desk fee audit using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed franchise desk fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Franchise desk fee audit Reference","text","REB08-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("cap-threshold-monitoring","REB09","Cap threshold monitoring","Execute cap threshold monitoring using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed cap threshold monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Cap threshold monitoring Reference","text","REB09-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("lease-renewal-commission","REB10","Lease renewal commission","Execute lease renewal commission using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed lease renewal commission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Lease renewal commission Reference","text","REB10-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("contingent-payment-tracking","REB11","Contingent payment tracking","Execute contingent payment tracking using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed contingent payment tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Contingent payment tracking Reference","text","REB11-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("closing-cash-reconciliation","REB12","Closing cash reconciliation","Execute closing cash reconciliation using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed closing cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Closing cash reconciliation Reference","text","REB12-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("agent-dispute-workflow","REB13","Agent dispute workflow","Execute agent dispute workflow using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed agent dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Agent dispute workflow Reference","text","REB13-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("commission-statements","REB14","Commission statements","Execute commission statements using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed commission statements decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Commission statements Reference","text","REB14-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]}),
feature("office-agent-profitability","REB15","Office agent profitability","Execute office agent profitability using listing and representation agreements, properties, transactions, closing statements, lease schedules, commission rates, agent splits, referrals, franchise fees, thresholds, and cash.","Produce a governed office agent profitability decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brokerage / Transaction","text","Brokerage / Transaction · Standard Case"],["caseReference","Office agent profitability Reference","text","REB15-2026-001"],["paidCommission","Paid Commission","currency",864000],["earnedCommission","Calculated Earned Commission","currency",1019520],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCommission",subjects:["Agreement library case","Property transaction registry case","Closing statement ingestion case","Gross commission calculation case","Co-broker split validation case"]})
]);
